-- einfaches Beispiel
create table t (
    id number generated always as identity
    start with 1000 increment by 1,
    text varchar2(50)
    );
    
drop table t;
    
insert into t(text) values('This table has an identity column');
select * from t;
insert into t(text) values('This table uses auto-increment');
select * from t;

-------------- GENERATED ALWAYS AS IDENTITY
drop table t;

create table t (
    id NUMBER GENERATED ALWAYS AS IDENTITY,
    text varchar2(50));

-- ohne PK    
insert into t(text) values('text');

-- mit PK geht schief
insert into t(id, text) values(3, 'text');

-- NULL
insert into t(id, text) values(NULL, 'text');

-------------- GENERATED BY DEFAULT
drop table t;

create table t (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    text varchar2(50));

-- ohne PK    
insert into t(text) values('text');
select * from t;
-- mit PK
insert into t(id, text) values(3, 'text');

-- NULL
insert into t(id, text) values(NULL, 'text');



-------------- GENERATED BY DEFAULT ON NULL
drop table t;

create table t (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    text varchar2(50));

-- ohne PK    
insert into t(text) values('text');
select * from t;
-- mit PK geht schief
insert into t(id, text) values(3, 'text');

-- NULL
insert into t(id, text) values(NULL, 'text');





drop table t purge;

-------------- Identity Columns werden als Sequenzen gespeichert
select * from user_objects;

-- Sequenzen anzeigen
select object_name, object_type
from user_objects;

-- Informationen zu den Identity Columns
select * from all_tab_identity_cols;

select table_name, column_name, generation_type, identity_options
from all_tab_identity_cols
where owner = '0815'
-- order by 1,2
;

